DELETE FROM USERS;
DELETE FROM GROUPS;
ALTER TABLE USERS AUTO_INCREMENT = 1;
ALTER TABLE GROUPS AUTO_INCREMENT = 1;
INSERT INTO USERS VALUES (DEFAULT, 'ivanov');
INSERT INTO GROUPS VALUES (DEFAULT, 'teamA');